Repository ColyberCompany/ColyberFlightController, pull requests merged in 2021-08, with the labels that each got.

#49 Adding feature to group tasks
  ColyberCopter/Common/TasksGroup.h
  ColyberCopter/src/TasksGroup.cpp
Labels: enhancement

#50 Motors does not work fix
  ColyberCopter/Motors/QuadXMotors.h
Labels: bug

#51 Sensors base class fix
  ColyberCopter/Common/FloatAxisVector.h
  ColyberCopter/CopterSetup.cpp
  ColyberCopter/Instances/MainInstances.h
  ColyberCopter/Instances/SensorInstances.h
  ColyberCopter/Interfaces/ISensorsData.h
  ColyberCopter/PositionAndRotation/RotationCalculation/MadgwickAHRS.h
  ColyberCopter/PositionAndRotation/RotationCalculation/MadgwickIMU.h
  ColyberCopter/Sensors/Base/Accelerometer.h
  ColyberCopter/Sensors/Base/Barometer.h
  ColyberCopter/Sensors/Base/GPS.h
  ColyberCopter/Sensors/Base/Gyroscope.h
  ColyberCopter/Sensors/Base/Magnetometer.h
  ColyberCopter/Sensors/Base/Rangefinder.h
  ColyberCopter/Sensors/Base/Sensor.h
  ColyberCopter/Sensors/HMC5883LAdapter.h
  ColyberCopter/Sensors/MPU6050Adapter.h
  ColyberCopter/Sensors/NoSensor.h
  ColyberCopter/Sensors/Sensor.h
  ColyberCopter/Sensors/SensorsMediator.h
  ColyberCopter/Sensors/SimpleHMC5883LHandler.h
  ColyberCopter/Sensors/SimpleMPU6050Handler.h
  ColyberCopter/Tasks.h
  ColyberCopter/src/HMC5883LAdapter.cpp
  ColyberCopter/src/MPU6050Adapter.cpp
  ColyberCopter/src/MadgwickAHRS.cpp
  ColyberCopter/src/MadgwickIMU.cpp
  ColyberCopter/src/SimpleHMC5883LHandler.cpp
  ColyberCopter/src/SimpleMPU6050Handler.cpp
Labels: bug

#53 MPU6050 handler refactoring. Tested.
  ColyberCopter/CopterSetup.cpp
  ColyberCopter/Sensors/SimpleMPU6050Handler.h
  ColyberCopter/src/SimpleMPU6050Handler.cpp
Labels: enhancement

#57 added quaternions and implemented getAbsoluteAcceleration method
  ColyberCopter/Common/Quaternion.h
  ColyberCopter/Interfaces/IAHRS.h
  ColyberCopter/Interfaces/IRotationCalculation.h
  ColyberCopter/PositionAndRotation/AHRS.h
  ColyberCopter/PositionAndRotation/RotationCalculation/MadgwickIMU.h
  ColyberCopter/src/AHRS.cpp
  ColyberCopter/src/MadgwickIMU.cpp
Labels: enhancement

#56 Switching to MadgwickAHRS
  ColyberCopter/CopterSetup.cpp
  ColyberCopter/PositionAndRotation/RotationCalculation/MadgwickAHRS.h
  ColyberCopter/PositionAndRotation/RotationCalculation/MadgwickBase.h
  ColyberCopter/PositionAndRotation/RotationCalculation/MadgwickIMU.h
  ColyberCopter/config.cpp
  ColyberCopter/config.h
  ColyberCopter/src/MadgwickAHRS.cpp
  ColyberCopter/src/MadgwickBase.cpp
  ColyberCopter/src/MadgwickIMU.cpp
  ColyberCopter/src/SimpleHMC5883LHandler.cpp
  ColyberCopter/src/StabilizeFlightMode.cpp
Labels: enhancement

#59 Function to show vector3
  ColyberCopter/Common/Utils.h
Labels: enhancement

#18 AltHold implementation
  ColyberCopter/CopterSetup.cpp
  ColyberCopter/FlightModes/AltHoldFlightMode.h
  ColyberCopter/FlightModes/StabilizeFlightMode.h
  ColyberCopter/Instances/SensorInstances.h
  ColyberCopter/Sensors/SimpleMS5611Handler.h
  ColyberCopter/config.cpp
  ColyberCopter/config.h
  ColyberCopter/src/AltHoldFlightMode.cpp
  ColyberCopter/src/PacketReceivedCallbacks.cpp
  ColyberCopter/src/SimpleMS5611Handler.cpp
  ColyberCopter/src/StabilizeFlightMode.cpp
Labels: enhancement

#60 Only barometer altitude calculation
  ColyberCopter/Common/Utils.h
  ColyberCopter/CopterSetup.cpp
  ColyberCopter/Interfaces/IAHRS.h
  ColyberCopter/Interfaces/IPositionCalculation.h
  ColyberCopter/PositionAndRotation/AHRS.h
  ColyberCopter/PositionAndRotation/PositionCalculation/AltitudeCalculation.h
  ColyberCopter/PositionAndRotation/PositionCalculation/NoPosCalcTemp.h
  ColyberCopter/src/Utils.cpp
Labels: enhancement

#63 Changing AHRS to INS
  ColyberCopter/CopterSetup.cpp
  ColyberCopter/Instances/MainInstances.h
  ColyberCopter/Interfaces/IAHRS.h
  ColyberCopter/Interfaces/IAltitudeCalculation.h
  ColyberCopter/Interfaces/IHorizontalPositionCalculation.h
  ColyberCopter/Interfaces/IPositionCalculation.h
  ColyberCopter/Libraries/MadgwickAHRS.h
  ColyberCopter/Libraries/MahonyAHRS.h
  ColyberCopter/NavigationSystem/INS.h
  ColyberCopter/PositionAndRotation/AHRS.h
  ColyberCopter/PositionAndRotation/PositionCalculation/AltitudeCalculation.h
  ColyberCopter/PositionAndRotation/PositionCalculation/NoPosCalcTemp.h
  ColyberCopter/PositionAndRotation/RotationCalculation/MadgwickAHRS.h
  ColyberCopter/PositionAndRotation/RotationCalculation/MahonyAHRS.h
  ColyberCopter/Tasks.h
  ColyberCopter/src/AHRS.cpp
  ColyberCopter/src/AltHoldFlightMode.cpp
  ColyberCopter/src/FailsafeScenarios.cpp
  ColyberCopter/src/INS.cpp
  ColyberCopter/src/MadgwickAHRS.cpp
  ColyberCopter/src/MahonyAHRS.cpp
  ColyberCopter/src/StabilizeFlightMode.cpp
Labels: enhancement, refactoring
